# fly.toml
app = "lfetch"
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"
  context = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true

[env]
  PORT = "8080"

[deploy]
  strategy = "immediate"
