       ?BBBBBBBBBBBBBBBB?       
      Y#BBBBBBBBBBBBBBBB#Y      
    .P#BBBBB##BBBBBBBBBBB#P.    
   ^B#BBBB#BY7G#BB#GB#BBBB#B^   
  !BBBBB#BY:   !GP~ ^5##BBBBB!  
 J#BBB#BJ.  :~   .    :YB#BBB#J 
J#BBBG7.  .7##G7   :!.  .JBBBB#J
 J#B5.  ~?.^#BB#B?.  !Y:  :GB#J 
  !BBGPG#BGGBBBBB#BPPG#BGPGBB!  
   ^B#BBBBBBBBBBBBBBBBBBBB#B^   
    .P#BBBBBBBBBBBBBBBBBB#P.    
      Y#BBBBBBBBBBBBBBBB#Y      
       ?BBBBBBBBBBBBBBBB?    
   
